# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 6af095b1c041d9d72a3bc7ea30b2261a1788ff00736aef6a09bc2eb96499a62a64b53699a46b8994dfadb40732892db8d8a56b11d11f373a5450e0330b5d868b

test:
  secret_key_base: c6fd04ec0bcf06512a248d3b0c283f832d62b694043f658121e554a6ca6f8c1a8f76178b21bb0a9de9c87405581bdfdd0fdb8b720eb0db54caff60502f3fb636

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
